-- CreateTable
CREATE TABLE "Message" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "text" TEXT NOT NULL,
    "author" TEXT NOT NULL DEFAULT 'Server',
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
